tradable_universe:
  master_list: data/tradable_etfs.csv
  symbols:
    - SPY
    - VTI
    - ACWI
    - BIL
    - XSD
    - IEFA
    - IEMG
    - AGG
    - GLD
    - USO
    - SHY
    - VTV
    - XBI
    - PBD
    - IBIT
    - QQQM
    - GTEK
    - CPER
